### ISSUE TITLE
Application working?

### ISSUE THREAD

**Issue by oguzhaneren33** [barkenikhil02/Suraksha#2]
I have a project assignment and I will get help from this project. But does it work completely error-free? What are the features of the application? Any chance you can send me the test application? I can't test it because I don't have a knowledge. Good day!

**Comment by barkenikhil02** [comment]
Hi,
You can fork and clone the project.
It is fully working developed on Flutter framework which uses dart language.
You can learn some basics of flutter and will become ready to run the app.
No need to worry about anything in the app. All SOS safety features are
implemented in app.
Thanks and Regards

**Comment by oguzhaneren33** [comment]
What features does it have? I have to plan accordingly.

**Comment by barkenikhil02** [comment]
Hi
You can check this by trying it.
Thanks
